import { Noto_Sans } from 'next/font/google'
import { dir } from 'i18next'
import { languages } from '@/app/i18n/settings'

export async function generateStatisParams() {
  return languages.map(lng => ({ lng }))
}

const noto = Noto_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ 
  children,
  params: {
    lng
  }
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={noto.className}>
        {children}
      </body>
    </html>
  )
}
